    
resources:
  - name: RemoteFile
    type: RemoteFile
    configuration:
      source: git_chaitanya
      fileLocation: 'https://github.com/ChaitanyaVootla/ymlTest/edit/master/pipelines.yml'
      fileName: 'pipelines2.yml'
      fileDateTime: 'dttm'
pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: bash
        type: bash
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          resources:
            - RemoteFile
