    
resources:
  - name: RemoteFile
    type: RemoteFile
    configuration:
      source: git_chaitanya
      fileLocation: 'https://github.com/ChaitanyaVootla/ymlTest/edit/master/pipelines.yml'
      fileName: 'pipelines.yml'
      fileDateTime: 'dttm'
  - name: FileSpec
    type: FileSpec
    configuration:      
      sourceArtifactory: docker_chaitanya
      pattern: 'test'
      aql: 'test'
      target: 'test'
      props: 'test'
      recursive: false
      flat: false
      excludePatterns: 'test'
      archiveEntries: 'test'
      sortBy: 'test'
      sortOrder: 'test'
      limit: 1
      offset: 1
  - name: Aql
    type: Aql
    configuration:
      sourceArtifactory: artifactoryIntegration
      query: 'asd'
  - name: BuildInfo 
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuild
      buildNumber: 123
  - name: DockerTagTest
    type: Image
    configuration:
      registry: artDocker
      imageName: demo/app
      imageTag: latest
      autoPull: false
pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: Bash_1
        type: Bash
        configuration:
          priority: 0
          outputResources:
            - name: DockerTagTest
        execution:
          onExecute:
            - write_output DockerTagTest "imageTag="$step_id
      - name: Bash_2
        type: Bash
        configuration:
          priority: 0
          inputResources:
            - name: DockerTagTest
            - name: Aql
        execution:
          onExecute:
            - echo "done"
      - name: Bash_3
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_2
          inputResources:
            - name: FileSpec
            - name: RemoteFile
          integrations:
            - name: artifactoryIntegration
            - name: git_chaitanya
        execution:
          onExecute:
            - echo "done"
#       - name: bash
#         type: bash
#         execution:
#           onExecute:
#             - echo "executing..."
#         triggeredBy:
#           resources:
#             - KubeCluster
#             - RemoteFile
#             - FileSpec
#       - name: CreateReleaseBundle
#         type: CreateReleaseBundle
#         configuration:
#           releaseBundleName: 'test'
#           releaseBundleVersion: 'test'
#           dryRun: false
#           sign: false
#           storeAtSourceArtifactory: 'test'
#           description: 'test'
#           releaseNotes:
#             content: 'test'
#             syntax: plain_text
#           inputResources:
#             - name: KubeCluster
#             - name: BuildInfo
#           inputSteps:
#             - name: bash
#           integrations:
#             - name: artifactoryIntegration
#           outputResources:
#             - name: RemoteFile
