resources:
  - name: git
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: git_OUT
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: git_OUT_2
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: git_OUT_COMMON
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: git_IN
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: git_SANDWICH
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: git_SANDWICH_2
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: buildInfo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1
  - name: buildInfo2
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1
  - name: buildInfo3
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1
  - name: buildInfo4
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1
  - name: buildInfo5
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1
pipelines: 
  - name: state_test_git
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: git
            - name: buildInfo2
            - name: buildInfo3
          outputResources:
            - name: git_OUT
            - name: buildInfo
        execution:
          onExecute:
            - pushd $res_git_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
            - sleep 10
            - echo 'https://github.com/ChaitanyaVootla/ymlTest/edit/master/pipelines.yml'
      
#       - name: run_file_restore
#         type: Bash
#         configuration:
#           inputSteps:
#             - name: testReport_u18
#         execution:
#           onExecute:
#             - printenv
  - name: IN
    steps:
      - name: IN_TEST
        type: Bash
        configuration:
          outputResources:
            - name: git
            - name: git_SANDWICH
          inputResources:
            - name: git_IN
            - name: buildInfo2
            - name: buildInfo3
            - name: buildInfo4
            - name: buildInfo5
        execution:
          onExecute:
            - sleep 10
      - name: IN_TEST_OUT
        type: Bash
        configuration:
          inputResources:
            - name: git_SANDWICH
          inputSteps:
            - name: IN_TEST
        execution:
          onExecute:
            - sleep 10
  - name: IN_2
    steps:
      - name: IN_TEST_2
        type: Bash
        configuration:
          inputResources:
            - name: buildInfo2
            - name: buildInfo3
            - name: buildInfo4
            - name: buildInfo5
          outputResources:
            - name: git
        execution:
          onExecute:
            - sleep 10
  - name: OUT
    steps:
      - name: OUT_TEST
        type: Bash
        configuration:
          inputResources:
            - name: git_OUT
            - name: buildInfo2
            - name: buildInfo3
            - name: buildInfo4
          outputResources:
            - name: git_OUT_2
            - name: git_OUT_COMMON
        execution:
          onExecute:
            - sleep 10
  - name: OUT_2
    steps:
      - name: OUT_TEST_2
        type: Bash
        configuration:
          inputResources:
            - name: git_OUT
            - name: buildInfo2
            - name: buildInfo3
            - name: buildInfo4
          outputResources:
            - name: git_OUT_2
            - name: buildInfo
        execution:
          onExecute:
            - sleep 10
  - name: OUT_LVL_2
    steps:
      - name: OUT_LVL_2_TEST
        type: Bash
        configuration:
          inputResources:
            - name: git_OUT_2
            - name: git_SANDWICH_2
            - name: git_OUT_COMMON
            - name: buildInfo2
            - name: buildInfo3
        execution:
          onExecute:
            - sleep 10
  - name: OUT_SANDWICH
    steps:
      - name: OUT_SANDWICH_TEST
        type: Bash
        configuration:
          inputResources:
            - name: git
            - name: buildInfo2
            - name: buildInfo3
            - name: buildInfo4
            - name: buildInfo5
          outputResources:
            - name: git_SANDWICH_2
        execution:
          onExecute:
            - sleep 10


  - name: trigger_test
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_3
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_2
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_4
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_3
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_5
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_6
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_4
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_7
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_5
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_8
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_9
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_10
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_11
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_7
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_12
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_9
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_13
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_4
        execution:
          onExecute:
            - sleep 60
            - echo "done"
  - name: orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test
    steps:
      - name: orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_
        type: Bash
        configuration:
          inputResources:
            - name: buildInfo2
            - name: buildInfo3
            - name: buildInfo4
            - name: buildInfo5
        execution:
          onExecute:
            - sleep 10

  - name: orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test2
    steps:
      - name: orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_2
        type: Bash
        execution:
          onExecute:
            - sleep 10
  - name: orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test3
    steps:
      - name: orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_orphan_test_3
        type: Bash
        execution:
          onExecute:
            - sleep 10




