    
resources:
  - name: KubeCluster
    type: KubeCluster
    configuration:
      kubernetesConfig: docker_chaitanya
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration
pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: bash
        type: bash
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          resources:
            - KubeCluster
