pipelines: 
  - name: trigger_test
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
        execution:
          onExecute:
            - sleep 60
            - echo "done"
  - name: state_test
    steps:
      - name: testReport_u18
        type: Bash
        execution:
          onExecute:
            - sudo chmod +x ./echoTest.sh
            - ./echoTest.sh
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv
