    
resources:
  - name: Image
    type: Image
    configuration:
       registry: docker_chaitanya
       imageName: imageRepo/imageName
       imageTag: initial
pipelines:
  - name: img_test_pipeline
    steps:
      - name: Bash_1
        type: Bash
        configuration:
          affinityGroup: bldGroupTest
          priority: 0
          outputResources:
            - name: Image
        execution:
          onExecute:
            - write_output Image "imageTag="$step_id
      - name: Bash_1_1
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_1
        execution:
          onExecute:
            - echo "done"
      - name: Bash_1_2
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_1
        execution:
          onExecute:
            - echo "done"
      - name: Bash_1_3
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_1
        execution:
          onExecute:
            - echo "done"
      - name: Bash_1_4
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_1
        execution:
          onExecute:
            - echo "done"
      - name: Bash_3
        type: Bash
        configuration:
          affinityGroup: bldGroupTest
          priority: 0
          inputSteps:
            - name: Bash_1
        execution:
          onExecute:
            - echo "done"
      - name: Bash_6
        type: Bash
        configuration:
          affinityGroup: bldGroupTest 
          priority: 0
          inputResources:
            - name: Image
        execution:
          onExecute:
            - echo "done"
      - name: Bash_7
        type: Bash
        configuration:
          affinityGroup: bldGroupTest 
          priority: 0
          inputSteps:
            - name: Bash_6
        execution:
          onExecute:
            - echo "done"
      - name: Bash_8
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_3
        execution:
          onExecute:
            - echo "done"
      - name: Bash_9
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_3
        execution:
          onExecute:
            - echo "done"
      - name: Bash_10
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: Bash_3
        execution:
          onExecute:
            - echo "done"
            
            
            
            
  - name: trigger_test
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
          outputResources:
            - name: Image
        execution:
          onExecute:
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
          inputSteps:
            - name: trigger_1
            - name: trigger_3
        execution:
          onExecute:
            - echo "done"
      - name: trigger_3
        type: Bash
        configuration:
          priority: 0
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - echo "done"
