resources:
  - name: git
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
pipelines: 
  - name: state_test_git
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: git
        execution:
          onExecute:
            - pushd $res_git_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
            - sleep 2
            - echo 'https://github.com/ChaitanyaVootla/ymlTest/edit/master/pipelines.yml'
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv


  - name: trigger_test
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          priority: 0
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_2
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_3
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_2
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_4
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_3
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_5
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_6
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_4
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_7
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_5
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_8
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_9
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_10
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_1
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_11
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_7
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_12
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_9
        execution:
          onExecute:
            - sleep 60
            - echo "done"
      - name: trigger_13
        type: Bash
        configuration:
          inputSteps:
            - name: trigger_4
        execution:
          onExecute:
            - sleep 60
            - echo "done"





