    
resources:
  - name: RemoteFile
    type: RemoteFile
    configuration:
      source: git_chaitanya
pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: bash
        type: bash
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          resources:
            - RemoteFile
