    
resources:
  - name: Image
    type: Image
    configuration:
       registry: docker_chaitanya
       imageName: imageRepo/imageName
       imageTag: initial
pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: Bash_1
        type: Bash
        configuration:
          affinityGroup: bldGroup 
          priority: 0
          outputResources:
            - name: Image
        execution:
          onExecute:
            - write_output Image "imageTag="$step_id
      - name: Bash_2
        type: Bash
        configuration:
          affinityGroup: bldGroup 
          priority: 0
          inputResources:
            - name: Image
        execution:
          onExecute:
            - echo "done"
