pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: bash
        type: bash
        configuration:
          affinityGroup: test_group
        execution:
          onExecute:
            - echo "executing..."
