    
resources:
  - name: RemoteFile
    type: RemoteFile
    configuration:
      source: git_chaitanya
      fileLocation: 'https://github.com/ChaitanyaVootla/ymlTest/edit/master/pipelines.yml'
      fileName: 'pipelines.yml'
      fileDateTime: 'dttm'
  - name: KubeCluster
    type: KubeCluster
    configuration:
      kubernetesConfig: docker_chaitanya
      bastionHostIP: 1.2.3.4
      bastionUser: sshUser
      bastionIntegrationName: sshKeyIntegration
  - name: FileSpec
    type: FileSpec
    configuration:      
      sourceArtifactory: docker_chaitanya
      pattern: 'test'
      aql: 'test'
      target: 'test'
      props: 'test'
      recursive: false
      flat: false
      excludePatterns: 'test'
      archiveEntries: 'test'
      sortBy: 'test'
      sortOrder: 'test'
      limit: 1
      offset: 1
  - name: BuildInfo 
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactoryIntegration
      buildName: myBuild
      buildNumber: 123
pipelines:
  - name: img_test_pipeline
    setup:
      runtime: onHost
    steps:
      - name: XrayScan
        type: XrayScan
        configuration:
          waitUntilFinish: false
          buildName: 'test'
          buildNumber: 'test'
#           integrations:
#             - name: artifactoryIntegration
          inputResources:
            - name: BuildInfo
              trigger: false 
#       - name: bash
#         type: bash
#         execution:
#           onExecute:
#             - echo "executing..."
#         triggeredBy:
#           resources:
#             - KubeCluster
#             - RemoteFile
#             - FileSpec
#       - name: CreateReleaseBundle
#         type: CreateReleaseBundle
#         configuration:
#           releaseBundleName: 'test'
#           releaseBundleVersion: 'test'
#           dryRun: false
#           sign: false
#           storeAtSourceArtifactory: 'test'
#           description: 'test'
#           releaseNotes:
#             content: 'test'
#             syntax: plain_text
#           inputResources:
#             - name: KubeCluster
#             - name: BuildInfo
#           inputSteps:
#             - name: bash
#           integrations:
#             - name: artifactoryIntegration
#           outputResources:
#             - name: RemoteFile
