resources:
  - name: git
    type: GitRepo
    configuration:
      gitProvider: gitResource
      path: ChaitanyaVootla/ymlTest
  - name: art
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: "1"
      buildNumber: 1
  - name: docker
    type: Image
    configuration:
      registry: docker
      sourceRepository: asd/asd
      imageName: someImageName
      imageTag: someImageTag
      autoPull: false
pipelines: 
  - name: state_test_git
    steps:
      - name: testReport_u18
        type: Bash
        configuration:
          inputResources:
            - name: git
            - name: art
            - name: docker
        execution:
          onExecute:
            - pushd $res_git_resourcePath
            - sudo chmod +x echoTest.sh
            - ./echoTest.sh
      
      - name: run_file_restore
        type: Bash
        configuration:
          inputSteps:
            - name: testReport_u18
        execution:
          onExecute:
            - printenv
